### ISSUE TITLE
当角度大于360度时，随着时间的减少，本该是白色的指针仍然是绿色

### ISSUE THREAD

**Issue by QeekDong** [xuanxuandaoren/DragCircleProgressView#2]
可以在这个方法里加入
private void startCountDown() {
     if (mTouchAngle == 0.0 & circleCount>0){
                        circleCount--; }
}

**Comment by xuanxuandaoren** [comment]
加了句这个代码 
 circleCount = mCurrentValue / mTotalValue;        

如果按照你这样改的话会出现跳过的情况 即从0.1直接变成359.9这样的 ，而且你写的时候用&&代替&会减少程序执行的时间 。

最后 谢谢你的建议
